site_name: ACCESS-Hive

# Needed to generate the canonical_url for each pages that are 
# then used to create the sitemap for search engine indexing
site_url: https://access-hive.org.au
# Git repository
repo_url: https://github.com/ACCESS-Hive/access-hive.github.io
repo_name: ACCESS-Hive
# Material default to a "master" branch, need to change to "main"
edit_uri: edit/main/docs
docs_dir: docs

# Theme
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: light
      primary: purple
      accent: deep orange
      toggle:
        # icon: material/toggle-switch-off-outline
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: purple
      accent: deep orange
      toggle:
        # icon: material/toggle-switch
        icon: material/weather-night
        name: Switch to light mode


  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes

  logo: assets/ACCESS_icon_HIVE.png
  favicon: assets/ACCESS_icon_HIVE.png
copyright: Copyright &copy; 2022 ACCESS-NRI

plugins:
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
  - search
  - macros
  - bibtex:
      bib_file: "references.bib"
  - events:
      events_dir: events/events

# Extensions
markdown_extensions: 
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - footnotes

# Navigation
nav:
  - Home: index.md
  - Getting Started: 
    - getting_started/index.md
    - ACCESS-OM2: getting_started/access-om2.md
  - Configurations: 
    - configurations/index.md
    - ACCESS-ESM: configurations/access-esm.md
    - ACCESS-CM: configurations/access-cm.md
    - ACCESS-AM: configurations/access-am.md
    - ACCESS-OM: configurations/access-om.md
    - ACCESS-S: configurations/access-s.md
  - Model Components: 
    - model_components/index.md
    - Atmosphere: model_components/atmosphere.md
    - Land: model_components/land.md
    - Ocean: model_components/ocean.md
    - Sea Ice: model_components/sea-ice.md
    - Aerosols and Atmospheric Chemistry: model_components/aerosols_atmospheric_chemistry.md
    - Biogeochemistry Land: model_components/bgc_land.md
    - Biogeochemistry Ocean: model_components/bgc_ocean.md
    - Coupler: model_components/coupler.md
  - Model Evaluation & Data: 
    - model_evaluation/index.md
    - Atmosphere: model_evaluation/atmosphere.md
    - Land: model_evaluation/land.md
    - Ocean Sea-ice: model_evaluation/ocean_seaice.md
    - Biogeochemistry Ocean: model_evaluation/bgc_ocean.md
    - Diagnostics: model_evaluation/diagnostics.md
    - Data processing: model_evaluation/data_processing.md
    - Data catalogs: model_evaluation/data_catalogs.md
  - Training: 
    - training/index.md
    - ACCESS training: training/ACCESS_training.md
    - Additional training: training/additional_training.md
  - Working Groups:
    - working_groups/index.md
  - Resources:
    - Data: resources/data.md
    - Glossary: resources/glossary.md
    - Policies: resources/policies.md
  - Events: 
    - events/index.md
    - Add Event: events/add_event.md
  - Forum: https://forum.access-hive.org.au
  - About:
    - Contact: about/contact.md
    - Support: about/support.md
    - Code of conduct: about/code_of_conduct.md
    - How to contribute: 
      - about/contribute/index.md
      - Edit on GitHub: about/contribute/direct_edit.md
      - Edit locally: about/contribute/local_edit.md
      - Stand-alone documentation: about/contribute/standalone_doc.md
      - Change the navigation: about/contribute/navigation_changes.md
      - Reviewers: about/contribute/reviewers_guidelines.md
    - License: License.md

# Footer
extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/ACCESS_NRI
      name: ACCESS-NRI on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/access-nri
      name: ACCESS-NRI on Linkedin
    - icon: fontawesome/brands/slack
      link: https://access-nri.slack.com/
      name: Join ACCESS-NRI Slack Channel
  analytics:
    provider: google
    property: G-2T6SQEH2CX
  supported: '<a href="https://access-hive.org.au/about/support"><i class="icon-supported" title="Supported by ACCESS-NRI"></i></a>'
  recommended: '<a href="https://access-hive.org.au/about/support"><i class="icon-recommended" title="Recommended by ACCESS-NRI"></i></a>'
  community: '<a href="https://access-hive.org.au/about/support"><i class="icon-community" title="Community Contributed"></i></a>'

extra_css:
  - css/access-nri.css
  - css/fontello.css
